### ISSUE TITLE
Referencing Windows.analytics throw compile error

### ISSUE THREAD

**Issue by tmchow** [segmentio/analytics-react#17]
Need to declare Windows interface as global to avoid compilation errors.

```
declare global {
    interface Window { analytics: any; }
}
```

**Comment by williamgrosset** [comment]
Hey @tmchow, thanks for bringing this up!

Are you including the analytics.js snippet in your `html` file? It should get bound onto `window`, but I know this was a similar issue with `Vue` and `Angular` apps where declaring the global was necessary. With most React apps, using `window.analytics.*` seems to work, but if your app is open-source I would like to dig into it a bit more - if not, no worries :) cheers!

**Comment by tmchow** [comment]
@williamgrosset We are indeed including the analytics.js snippet in our index.html file. It definitely wasn’t bound to `window.analytics.*` without the declaration I mentioned. 

Our app isn’t open source so I can’t share it.

**Comment by williamgrosset** [comment]
Added https://github.com/segmentio/analytics-react/commit/6b044435f43caa5dc9aeecdacca0431d18360692.
