### ISSUE TITLE
What is the purpose of this repo?

### ISSUE THREAD

**Issue by iMerica** [segmentio/analytics-react#18]
Hi,

I had a look at the README and the source code and can't figure out why this repo exists. I can't find a single importable React component in the source code. It's just an example project using Create React App.  Why have a package on NPM at all?

**Comment by williamgrosset** [comment]
Hi @iMerica,

Thanks for reaching out! The purpose of this repo is to help developers with a jumpstart guide for Analytics.js and React. We cloned the create-react-app repo and added Analytics.js + react-routing as a boilerplate for users who want to get started with Segment. This package isn't published to NPM, but the next evolution of this repo would be to create an importable React component that you can use within your app. Cheers!
