### ISSUE TITLE
staging vs production in Create React App?

### ISSUE THREAD

**Issue by joshpitzalis** [segmentio/analytics-react#19]
On segmnet, you suggest creating two sources for different environments.

For this package, you have to put the tag in the public folder.

As far as I understand Create react app doesn't let you use environment variable in the public folder.

This means I have to manually copy and paste the script tag in every time I want to switch between environments. If I mess this up and forget just once it's going to introduce a bunch of nonsense into my analytics. Is there a better way to do this?

Why is this repo labelled react if we just use the same js tag as everyone else?

**Comment by joshpitzalis** [comment]
Nevermind.

The solution was super straight forward.

replace this line in the html script
` analytics.load(%REACT_APP_SEGMENT%);`

and create a variable in a .env folder
` REACT_APP_SEGMENT='xxx'`

To be fair, this was the first thing I tried, it didn't work. Today it worked like a charm. So it was just an unrelated build issue I was having that was the problem.

**Comment by joshpitzalis** [comment]
Nope. 

This doesn't actually work

`Uncaught ReferenceError: xxx (my segment id) is not defined`

**Comment by smithmr** [comment]
@joshpitzalis 

This is working. In your CI/CD you need to make sure that the naming is the same. 

Also when you start your app on localhost you should do it like this.

`REACT_APP_SEGMENT=DEV_KEY react-scripts start`
Put that line in your package.json and whenever you start the app it will have the dev stuff.

In your CI/CD just make sure you set the dev and prod env variables with the same name.

**Comment by williamgrosset** [comment]
Thanks for the proactive jump on this @smithmr! :) Glad to hear you have it working on your end. @joshpitzalis let me know if you still have issues!

**Comment by joshpitzalis** [comment]
Not sure why this was closed.

I managed to find a solution for anyone else struggling with the same.

```
<script>
    !function () {
      var analytics = window.analytics = window.analytics || []; if (!analytics.initialize) if (analytics.invoked) window.console && console.error && console.error("Segment snippet included twice."); else {
        analytics.invoked = !0; analytics.methods = ["trackSubmit", "trackClick", "trackLink", "trackForm", "pageview", "identify", "reset", "group", "track", "ready", "alias", "debug", "page", "once", "off", "on"]; analytics.factory = function (t) { return function () { var e = Array.prototype.slice.call(arguments); e.unshift(t); analytics.push(e); return analytics } }; for (var t = 0; t < analytics.methods.length; t++) { var e = analytics.methods[t]; analytics[e] = analytics.factory(e) } analytics.load = function (t, e) { var n = document.createElement("script"); n.type = "text/javascript"; n.async = !0; n.src = "https://cdn.segment.com/analytics.js/v1/" + t + "/analytics.min.js"; var a = document.getElementsByTagName("script")[0]; a.parentNode.insertBefore(n, a); analytics._loadOptions = e }; analytics.SNIPPET_VERSION = "4.1.0";
        analytics.load(`%REACT_APP_SEGMENT_ID%`);
        analytics.page();
      }
    }();
  </script>
```

so you format the env variable like so `analytics.load(`%REACT_APP_SEGMENT_ID%`);`

Then in your .env file you have
```
REACT_APP_SEGMENT_ID="YdjXXXXPb4"
```

Now you can swap out staging trackers and productions trackers along with all you other staging/production variables.

**Comment by williamgrosset** [comment]
Great to hear! Also, instead of manually swapping write keys based off environment, I recommend using `process.env.NODE_ENV` to determine which key to use.

The above is worth mentioning in the doc. 👍
