### ISSUE TITLE
Running segment on localhost:3000

### ISSUE THREAD

**Issue by bdacoscos** [segmentio/analytics-react#24]
I'm trying to test my Segment configuration on localhost:3000, but I'm not getting any data coming in. Is it not possible to use localhost as a source?

**Comment by bdacoscos** [comment]
Whoops! I'm going to close this out since I have been successful in running other examples with my own write key.

**Comment by YuraEremok** [comment]
@bdacoscos I still don't understand how you run it on localhost.How did you use own write key?)

**Comment by DivyanshBatham** [comment]
@bdacoscos How did you manage to select localhost as a source?
